### PR TITLE
Midi 33: ECG autoencoder

### PR DESCRIPTION
**Pull request by SamuelJanas**
[MIDI-33](https://sacrebleu.atlassian.net/browse/MIDI-33)

[MIDI-33]: https://sacrebleu.atlassian.net/browse/MIDI-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by SamuelJanas** [comment]
## Results:
expected

Results(10 epochs of training) are not perfect although they learned quite a lot looking at loss function only.
I will be looking at some papers to find better components to put in the encoder/decoder. At first glance [this](https://www.frontiersin.org/articles/10.3389/fphys.2022.961724/full) looks promising.

Edit: Since I coulnd't find a place for the legend on the chart that didn't look horrendous:
**blue/green** - original signal
**red/orange** - reconstructed signal (dashed lines for colorblind people)
**left** for channel 0 of the signal, **right** for channel 1

**Comment by roszcz** [comment]
Nice! Can you look for data samples where the ECG signal contains clearly visible heart beats? Right now it looks like you tested mostly on noisy parts of the signal :)

**Comment by JasiekKaczmarczyk** [comment]
> ## Results:
> 
> expected
> 
> Results(10 epochs of training) are not perfect although they learned quite a lot looking at loss function only. I will be looking at some papers to find better components to put in the encoder/decoder. At first glance [this](https://www.frontiersin.org/articles/10.3389/fphys.2022.961724/full) looks promising.
> 
> Edit: Since I coulnd't find a place for the legend on the chart that didn't look horrendous: **blue/green** - original signal **red/orange** - reconstructed signal (dashed lines for colorblind people) **left** for channel 0 of the signal, **right** for channel 1

This paper might be good for your use case: https://arxiv.org/pdf/2210.13438.pdf. It's about high fidelity audio compression using Autoencoder architecture. I think audio and ECG signals should be pretty similar.

**Comment by SamuelJanas** [comment]
Not many changes made but, I've added a heuristic to visualization function. The results look more promising right now :sweat_smile:

heuristic hertbeat

**Comment by roszcz** [comment]
@SamuelJanas Here's an error I'm getting when training on ecg:

```sh
$ python train.py model.embedding_size=8 train.epochs=10 train.lr=1e-4 model.type=ECG_AE dataset.name=ltafdb


  File "/home/hagrid/workson/autoencoders-demo/train.py", line 194, in main
    train(cfg, autoencoder, loss_function, train_loader, test_loader)
  File "/home/hagrid/workson/autoencoders-demo/train.py", line 34, in train
    train_ecg_autoencoder(cfg, autoencoder, loss_function, train_loader, test_loader)
  File "/home/hagrid/workson/autoencoders-demo/train.py", line 82, in train_ecg_autoencoder
    first_layer = autoencoder.encoder.conv[0]
  File "/home/hagrid/.virtualenvs/autoencoders-demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ECG_Encoder' object has no attribute 'conv'
```

Let me know if it works for you!

**Comment by SamuelJanas** [comment]
> @SamuelJanas Here's an error I'm getting when training on ecg:
> 
> ```shell
> $ python train.py model.embedding_size=8 train.epochs=10 train.lr=1e-4 model.type=ECG_AE dataset.name=ltafdb
> 
> 
>   File "/home/hagrid/workson/autoencoders-demo/train.py", line 194, in main
>     train(cfg, autoencoder, loss_function, train_loader, test_loader)
>   File "/home/hagrid/workson/autoencoders-demo/train.py", line 34, in train
>     train_ecg_autoencoder(cfg, autoencoder, loss_function, train_loader, test_loader)
>   File "/home/hagrid/workson/autoencoders-demo/train.py", line 82, in train_ecg_autoencoder
>     first_layer = autoencoder.encoder.conv[0]
>   File "/home/hagrid/.virtualenvs/autoencoders-demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'ECG_Encoder' object has no attribute 'conv'
> ```
> 
> Let me know if it works for you!

Fixed! I changed the name from conv to layers to be more descriptive but forgot about its' use in `train.py`

**Comment by roszcz** [comment]
@SamuelJanas I got a different error now :)

```sh
Train Epoch: 10 [729600/730278 (100%)]  Loss: 10113.378823
====> Test set loss: 8057.3782
Error executing job with overrides: ['model.embedding_size=8', 'train.epochs=10', 'train.lr=1e-4', 'model.type=ECG_AE', 'dataset.name=ltafdb']
Traceback (most recent call last):
  File "/home/hagrid/workson/autoencoders-demo/train.py", line 197, in main
    visualize_ecg_reconstruction(cfg, autoencoder, test_loader)
  File "/home/hagrid/.virtualenvs/autoencoders-demo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hagrid/workson/autoencoders-demo/visualizations.py", line 66, in visualize_ecg_reconstruction
    reconstructions = autoencoder.model(to_plot_tensor)
  File "/home/hagrid/.virtualenvs/autoencoders-demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ECG_autoencoder' object has no attribute 'model'
```

**Comment by SamuelJanas** [comment]
> @SamuelJanas I got a different error now :)
> 
> ```shell
> Train Epoch: 10 [729600/730278 (100%)]  Loss: 10113.378823
> ====> Test set loss: 8057.3782
> Error executing job with overrides: ['model.embedding_size=8', 'train.epochs=10', 'train.lr=1e-4', 'model.type=ECG_AE', 'dataset.name=ltafdb']
> Traceback (most recent call last):
>   File "/home/hagrid/workson/autoencoders-demo/train.py", line 197, in main
>     visualize_ecg_reconstruction(cfg, autoencoder, test_loader)
>   File "/home/hagrid/.virtualenvs/autoencoders-demo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/hagrid/workson/autoencoders-demo/visualizations.py", line 66, in visualize_ecg_reconstruction
>     reconstructions = autoencoder.model(to_plot_tensor)
>   File "/home/hagrid/.virtualenvs/autoencoders-demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'ECG_autoencoder' object has no attribute 'model'
> ```

I'm sorry, another thing that I overlooked. Should be **fixed**. I managed to make it run **AND** finish successfully. 😅

**Review by roszcz — APPROVED** [review]

**Pull request merged**
